name = "AutoGen"
uuid = "330ca4ee-aa6c-4451-8119-cff3f569b8e7"
authors = ["Chad Scherrer <chad.scherrer@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
